# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5224340fb4434f103047228ecbba01fb59d6fa254ba332cf6d7c68b7e8865582b897dce061f94ed968cd14805d7f5d36600fb9695b694e58fd72e740f487e4

test:
  secret_key_base: 9a876d552d3dcc65b1d86cefffd80f12fb01ff0121267c7aa91d68272d509fc47de8a6d803e77e8146505eef1258d60933ae7dfc7f097010c0ccae76d8d43198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
