# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dad814e60813da2e60ca98001b4f6d8418b1e86d4d285a1580a6ce4a01bde6780f5ec159d87b81fb09af1c30f0a8a3a930e6ba1bb5bb2d61bb3491e36cc21e0

test:
  secret_key_base: 3ea0d138a61404e25392180c59fb6a988abd24b4a09f0701bd5d641b25fbb7508a74629f4112089b65a3531ded28c6ece4b1f364602763a7babc350abf428b1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
